function stim_processed = findStim(stim_file, bin_width)
% Extracts stimulus info from text file generated by AT software
% Also rounds stim times based on the width of a bin in the given monitor
% files to enable searching for the stim onset

%% Import text file and separate components

%Import data file
stim_raw = importdata(stim_file, ' ');

%Initialize cell for holding reformatted txt data
stim_processed = cell(length(stim_raw),2);

%% Reformat stim data to find stimuli in monitor data
month_dict = {'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'};

%Split day info into components

for i = 1:length(stim_raw)
    
    %Separate/reformat date
    stim_day = stim_raw{i,1}(4:5);
    if stim_day (1) == '0'
        stim_day = stim_day(2);
    end
    
    stim_month = str2double(stim_raw{i,1}(1:2));
    stim_month = month_dict{stim_month};
    
    stim_yr = stim_raw{i,1}(9:10);
    
    stim_processed{i,1} = [stim_day, ' ', stim_month, ' ', stim_yr];
    
    % Round stim delivery (down) to nearest bin
    stim_secs = str2double(stim_raw{i,1}(end-1:end));

    
    if bin_width==0.5        
        % Round to previous 30 second stim delivery

        if stim_secs >= 30
            stim_secs = '30';
        else
            stim_secs = '00';
        end
    
    elseif bin_width==1
        % Round to 1 min window
        stim_secs = '00';
        
    else
        % Assume something weird is going on and throw an error
        error('Bin width neither 1 min nor 30 sec. Check yo data fool.')
        
    end
    
    stim_processed{i,2} = [stim_raw{i,1}(end-7:end-2),stim_secs];
    
end