function stim_processed = findStim(stim_file)
% Extracts stimulus info from text file generated by AT software

%% Import text file and separate components

%Import data file
stim_raw = importdata(stim_file, ' ');

%Initialize cell for holding reformatted txt data
stim_processed = cell(length(stim_raw),2);

%% Reformat stim data to find stimuli in monitor data
month_dict = {'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'};

%Split day info into components

for i = 1:length(stim_raw)
    
    %Separate/reformat date
    stim_day = stim_raw{i,1}(4:5);
    if stim_day (1) == '0'
        stim_day = stim_day(2);
    end
    
    stim_month = str2double(stim_raw{i,1}(1:2));
    stim_month = month_dict{stim_month};
    
    stim_yr = stim_raw{i,1}(9:10);
    
    stim_processed{i,1} = [stim_day, ' ', stim_month, ' ', stim_yr];
    
    % Round down to previous 30 second stim delivery
    stim_secs = str2double(stim_raw{i,1}(end-1:end));
    
    if stim_secs >= 30
        stim_secs = '30';
    else
        stim_secs = '00';
    end
    
    
    stim_processed{i,2} = [stim_raw{i,1}(end-7:end-2),stim_secs];
    
end